[[main]]
name = 'Posts'
pageRef = '/'
weight = 10

[[main]]
name = 'Tags'
pageRef = '/tags'
weight = 20

[[main]]
name = 'Services'
pageRef = '/services'
weight = 30

[[main]]
name = 'About'
pageRef = 'about'
weight = 40
